import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.IdAlreadyInUseException;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMonokaiProContrastIJTheme;
import javax.swing.JOptionPane;
import java.awt.*;


public class HuffmanApp extends javax.swing.JFrame {

    /**
     * Creates new form HuffmanApp
     */
    public HuffmanApp() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Compressor Huffman");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txPlano = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComp = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taComp = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDecomp = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btEncode = new javax.swing.JButton();
        btDecode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENCODE DECODE HUFFMAN");

        txPlano.setColumns(20);
        txPlano.setRows(5);
        jScrollPane1.setViewportView(txPlano);

        txtComp.setColumns(20);
        txtComp.setRows(5);
        jScrollPane2.setViewportView(txtComp);

        jScrollPane3.setViewportView(taComp);

        jScrollPane4.setViewportView(taDecomp);

        jLabel2.setText("Texto comprimido:");

        jLabel3.setText("Texto a comprimir: ");

        jLabel4.setText("Texto descomprimido:");

        jLabel5.setText("Texto a descomprimir: ");

        btEncode.setText("Comprimir");
        btEncode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEncodeMouseClicked(evt);
            }
        });

        btDecode.setText("Descomprimir");
        btDecode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDecodeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDecode)
                                    .addComponent(btEncode)))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEncode)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btDecode)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btEncodeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        HuffmanTree arbol = new HuffmanTree(txPlano.getText());
        String codificado = arbol.encode();
        taComp.setText(codificado);
        crearGrafo(txPlano.getText());
    }                                     

    private void btDecodeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if(txPlano.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Primero codifique el mensaje");
        }
        else {
            HuffmanTree arbol = new HuffmanTree(txPlano.getText());
            String codificado = arbol.encode();
            String decodificado = arbol.decode(codificado);
            taDecomp.setText(decodificado);
            crearGrafo(txPlano.getText());
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HuffmanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HuffmanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HuffmanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HuffmanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        FlatMonokaiProContrastIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HuffmanApp().setVisible(true);
        });
        
        
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btDecode;
    private javax.swing.JButton btEncode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane taComp;
    private javax.swing.JTextPane taDecomp;
    private javax.swing.JTextArea txPlano;
    private javax.swing.JTextArea txtComp;
    // End of variables declaration
    public static void crearGrafo(String text) {
        HuffmanTree arbol = new HuffmanTree(text);
        arbol.encode();
        System.setProperty("org.graphstream.ui", "swing");
        // Crear un grafo
        Graph graph = new SingleGraph("Aplicacion");
        // Establecer la hoja de estilo para la representación visual de los nodos y las aristas
        graph.setAttribute("ui.stylesheet", styleSheet);

        // Para visualizar el grafo en una ventana con tamaño personalizado
        addNodesToGraph(arbol.getRoot(),graph,0,0);
        Viewer viewer = graph.display();
        viewer.disableAutoLayout();

    }
    private static void addNodesToGraph(Nodo current, Graph graph, double x, double y) {
        if (current != null) {
            try {// Agregar el nodo actual al grafo
                Node node = graph.addNode(String.valueOf(current.getData()));
                node.setAttribute("ui.label", current.getData());
                node.setAttribute("xy", x, y);
                double leftX = x - 10 * Math.pow(2,current.getHeight());
                double rightX = x + 10 * Math.pow(2,current.getHeight());
                double childY = y - 100;

                // Agregar los nodos hijos recursivamente
                if (current.getLeft() != null) {
                    addNodesToGraph(current.getLeft(), graph, leftX, childY);
                    Edge edge = graph.addEdge((current.getData() + "-" + current.getLeft().getData()),
                            String.valueOf(current.getData()), String.valueOf(current.getLeft().getData()));
                    edge.setAttribute("ui.label", "0");
                }
                if (current.getRight() != null) {
                    addNodesToGraph(current.getRight(), graph, rightX, childY);
                    Edge edge = graph.addEdge((current.getData() + "-" + current.getRight().getData()),
                            String.valueOf(current.getData()), String.valueOf(current.getRight().getData()));
                    edge.setAttribute("ui.label", "1");
                }
            }
            catch (IdAlreadyInUseException e) {
                current.setData(current.getData().concat("."));
                addNodesToGraph(current,graph,x,y);
            }
        }
    }
    protected static String styleSheet = "node {" +
            "    shape: circle;" +
            "    size: 40px;" +
            "    text-size: 12;" +
            "    fill-mode: plain;" +
            "    fill-color: orange;" +
            "    stroke-mode: plain;" +
            "    stroke-color: black;" +
            "    stroke-width: 1px;" +
            "}" +
            "edge {" +
            "    arrow-shape: arrow;" +
            "    arrow-size: 20px, 4px;" +
            "    text-size: 18; " +
            "    text-color: black;" +
            "}" +
            "node.root {" +
            "    fill-color: yellow;" +
            "}";
}
